// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/hertz-contrib/swagger"
	swaggerFiles "github.com/swaggo/files"
	_ "hertz-web/docs"
	"hertz-web/swagger_demo"
)

func main() {
	h := server.Default()

	h.GET("/user/get", swagger_demo.GetUser)
	h.POST("/user/add", swagger_demo.AddUser)
	h.DELETE("/user/delete", swagger_demo.DeleteUser)
	h.GET("/user/get/:id", swagger_demo.GetUserByID)

	url := swagger.URL("http://localhost:8888/swagger/doc.json") // The url pointing to API definition
	h.GET("/swagger/*any", swagger.WrapHandler(swaggerFiles.Handler, url))

	h.Spin()
}
